### ISSUE TITLE
duplicate implicite advice calls on class hierarchy

### ISSUE THREAD

**Issue by Cyrille37** [okapi-web/php-aop#33]
Hi,

While coding on #30 I've observed a bad behavior with classes hierarchy and implicite Advice.

I thought that:
- with a Class hierarchy as A <- B <- C
- and only one method defined as C.hellowWord()
- and a implicit Aspect that match all methods of all classes A, B & C.

Then
- For one call of an A.hellowWord() instance,
    it must have only one calls of the Advice's method.
- For x calls of an A instance proxied method,
    it must have x calls of the Advice's method.

But it's not the case :disappointed: 

I wrote an UnitTest for demonstration in commit [implicite-advice_duplicate-call-class-hierachy](https://github.com/okapi-web/php-aop/commit/f869ad6c8699755969c95b0702902ebc784c4cbe). In the TestCase for 2 calls of A.method() with got 6 calls of the Advice method.

I haven't come up with an idea for the diagnosis yet ... keep searching & thinking ...

**Comment by WalterWoshid** [comment]
Hi @Cyrille37,

not quite sure what the problem is, but I'll have a look at it myself.

**Comment by WalterWoshid** [comment]
I see what the problem is. This is quite complicated. I'll try to break it down in simpler steps:

- TargetClassA has following structure:
```php
TargetClassC::helloWorld() // Root method
TargetClassB::helloWorld() // Inherited from TargetClassC
TargetClassA::helloWorld() // Inherited from TargetClassB
```

- If any class has the `helloWorld()` method from `TargetClassC`, it will be woven.
- A woven class will copy all methods that should be matched
- Example: TargetClassA (woven):
![image](https://github.com/okapi-web/php-aop/assets/36635504/1ab245f8-fcce-4e72-9028-fd37507f109d)

- This makes it so that every `TargetClass*::helloWorld()` method call, will always trigger the aspects `validateContent` advice. Because we have 3 `TargetClass` classes, it will be run 3 times for each `helloWorld()` method call. Because you called it twice, it will be run 6 times, thats the reason that the stack trace shows 6 entries.

I should implement a check if the class has defined the method itself or not and only then apply the advice. 

Also what if, for example, TargetClassB has also a `helloWorld()` method, that calls `parent::helloWorld()`, should the advice intercept both methods or only the top-most method?

**Comment by WalterWoshid** [comment]
If I replace `getMethods()` in `Okapi\Aop\Core\Matcher\AdviceMatcher\MethodMatcher` on line `31` with `getImmediateMethods()`, the test will succeed. But the `TraitAdvice` test will fail and I don't want that, I will test it further.

**Comment by WalterWoshid** [comment]
I have implemented my own `getImmediateMethods()` method which doesn't include traits and now it will only be called 2 times, instead of 6 times, see the new `ClassHierarchyOnlyInvokedOnceTest`.

Thank you for finding this bug :)

Release: `okapi/aop:1.2.4`

**Comment by Cyrille37** [comment]
It works :-)
